# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploy to GCP bucket

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: abinmn/gcp-storage-bucket-action@v1.0
      with:
        service_key: "${{ secrets.service_key }}"
        project: marketing
        build_folder: "${{ github.workspace }}"
        bucket_name: www.excelmec.org
        home_page_path: index.html
        error_page_path: index.html
